# Generated by Django 6.0.5 on 2026-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start_time', models.DateTimeField()),
                ('category', models.CharField(blank=True, default='general', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration_hours', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('activity_date', models.DateField()),
                ('category', models.CharField(blank=True, default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='default', max_length=64, unique=True)),
                ('sleep', models.FloatField(default=8)),
                ('work', models.FloatField(default=8)),
                ('eat', models.FloatField(default=1.5)),
                ('exercise', models.FloatField(default=1)),
                ('prayer', models.FloatField(default=0.5)),
                ('read', models.FloatField(default=1)),
                ('entertainment', models.FloatField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
