# Generated by Django 6.0.5 on 2026-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='daily_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='pomodoro_minutes',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
